# Generated by Django 3.1.7 on 2021-03-13 15:38

from django.db import migrations, models
import django.db.models.deletion
import guests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('formal', 'formal'), ('fun', 'fun'), ('dimagi', 'dimagi')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('save_the_date_sent', models.DateTimeField(blank=True, default=None, null=True)),
                ('save_the_date_opened', models.DateTimeField(blank=True, default=None, null=True)),
                ('invitation_id', models.CharField(db_index=True, default=guests.models._random_uuid, max_length=32, unique=True)),
                ('invitation_sent', models.DateTimeField(blank=True, default=None, null=True)),
                ('invitation_opened', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_invited', models.BooleanField(default=False)),
                ('is_invited_to_church', models.BooleanField(default=False)),
                ('is_attending', models.NullBooleanField(default=None)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('is_attending', models.NullBooleanField(default=None)),
                ('special_diet', models.CharField(blank=True, choices=[('gluten_free', 'gluteeniton'), ('milk_free', 'maidoton'), ('vegetarian', 'vege')], max_length=20, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.party')),
            ],
        ),
    ]
