# Generated by Django 3.1.7 on 2021-03-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='special_diet',
            new_name='diet',
        ),
    ]
